arch: amd64

language: java

jdk: oraclejdk15

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - name: "Xenial Linux"
      os: linux
      dist: xenial

script:
  - java --version
  - ./mvnw clean verify
  - ./mvnw clean install
  - ./mvnw test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - "saurab.mish@gmail.com"
    on_success: never
    on_failure: always
